In [5]:
import numpy as np

In [15]:
#question 1
arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
filtered_array = []
for element in arr:
    for number in element:
        if number%2 == 0:
            filtered_array.append(True)
        else:
            filtered_array.append(False)

newarray = arr[filtered_array]
newarray

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 12

In [103]:
#question 2.1
emptylist = []
def zeros(array):
    return np.zeros((8,8), dtype = int)
zerolist = zeros(emptylist)
zerolist

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [91]:
#question 2.2
rows = 8
def oddcheckerboard(array):
    for number in range(rows): #for each row with indexes from 0-7, 8 total rows ...
        lengthindex = range(len(array[number])) #length index is the list of numbers given by the length of that row (in this case it'll be indexes 0-7)
        if number%2 == 0: #if the row number is odd (index is even), then ...
            for index in lengthindex: #for each number within the selected row, ... 
                if index%2 == 0: #if the index of the length is even (number is odd) then ...
                    array[number, index] = 1  #replaces that index in that row in the array with 1
    return array                 
oddcheckerboard(zerolist)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [95]:
#question 2.3
def evencheckerboard(array):
    for number in range(rows): #for each row with indexes from 0-7, 8 total rows ...
        lengthindex = range(len(array[number])) #length index is the list of numbers given by the length of that row (in this case it'll be indexes 0-7)
        if number%2 != 0: #if the row number is even (index is odd), then ...
            for index in lengthindex: #for each number within the selected row, ... 
                if index%2 != 0: #if the index of the length is odd (number is even) then ...
                    array[number, index] = 1  #replaces that index in that row in the array with 1
    return array   
evencheckerboard(zerolist)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [105]:
#question 2.4
def reversecheckerboard(array):
    for number in range(rows): #for each row with indexes from 0-7, 8 total rows ...
        lengthindex = range(len(array[number])) #length index is the list of numbers given by the length of that row (in this case it'll be indexes 0-7)
        if number%2 == 0: #if the row number is odd (index is even), then ...
            for index in lengthindex: #for each number within the selected row, ... 
                if index%2 != 0: #if the index of the length is odd (number is even) then ...
                    array[number, index] = 1  #replaces that index in that row in the array with 1
        else:   #if the row number is even (index is odd), then ...
            for index in lengthindex: #for each number within the selected row, ... 
                if index%2 == 0: #if the index of the length is even (number is odd) then ...
                    array[number, index] = 1  #replaces that index in that row in the array with 1
    return array    
reversecheckerboard(zerolist)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [215]:
#question 3
universe = np.array(['galaxy', 'clusters'])
space = " "
def expansion(array):
    for word in array:  #for each word in the array
        counter = range(len(word))
        for number in counter:  #iterates through each letter in the word
            np.insert(word, number, space)
expansion(universe)

IndexError: index 2 is out of bounds for axis 0 with size 1

In [195]:
#question 4
np.random.seed(42)
planets = np.random.randint(100, 1000, (5, 5))
def secondlargest(array):
    for 
        np.unique(array)[-2]
secondlargest(planets)
planets

array([[202, 535, 960, 370, 206],
       [171, 800, 120, 714, 221],
       [566, 314, 430, 558, 187],
       [472, 199, 971, 763, 230],
       [761, 408, 869, 443, 591]])

In [147]:
new = np.array([[1,2,3], [4,5,6]])
new[:,0]

array([1, 4])

In [155]:
k = np.array([[ 35,  48,  63],
           [ 60,  77,  96],
           [ 91, 112, 135]])
i = np.unique(k)[-2]
i

112